version: '3.7'
services:
  mysql:
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=mydb
